language: java
jdk:
  - oraclejdk9
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/
script: ./gradlew clean build
deploy:
  provider: releases
  file_glob: true
  file: build/distributions/pirarucu-jvm*.zip
  api_key: $GITHUB_API_KEY
  skip_cleanup: true
  on:
    tags: true
